
import React, { useState } from 'react';
import './TermsAndConditions.css'; 

const TermsAndConditions = () => {
  const [checkedTerms, setCheckedTerms] = useState(false);
  const [checkedPrivacy, setCheckedPrivacy] = useState(false);

  const handleTermsChange = () => {
    setCheckedTerms(!checkedTerms);
  };
  const handlePrivacyChange = () => {
    setCheckedPrivacy(!checkedPrivacy);
  };
  return (
    <>
        <div className="terms-container">
      <p id='one'>Terms and Conditions</p>
      <p>Revision 5.3</p>
      <p>
        <h2>DigiKey Terms of Use and Conditions of Order</h2>
      </p>
      <p><strong>DATE OF LAST MODIFICATION</strong></p>
      <p><b>2024-03-26</b></p>
      <p>
        <b>Digi-Key Corporation (DBA DigiKey), together with its subsidiaries and affiliates, (collectively, "DigiKey"), operates <a href='www.digikey.in'>www.digikey.in</a> and a portfolio of other websites, including without limitation the DigiKey Tech-Xchange website, the eewiki.net website, the maker.io website and project sites provided by DigiKey, including www.digikey.in/en/maker (collectively "Project Sites"), and webstores that may be branded using the names of other entities and embedded in the websites of those other entities (collectively the “Site”). The Site provides online access to information about products and services, including without limitation, Chip Outpost products, and products and services offered through DigiKey’s marketplace program, available from DigiKey (collectively, the "Product(s)"); facilitates project sharing and management; provides access to applications engineering services about Products; may provide Communication Services (as defined Section 8 below); and facilitates transactions for the purchase of Products by itself and in conjunction with third- party applications using proprietary DigiKey web services ("Web Services Applications"), and in conjunction with third parties and their websites through DigiKey provided webstores (collectively the "Services").</b>
      </p>
      <p><b>By accessing, visiting, browsing, using or interacting or attempting to interact with any part of the Site or any Software (as defined below), program or Services on the Site you agree on your behalf personally, and on behalf of any entity for which you are an agent or you appear to represent, (collectively and individually "you," "your," or "user") to each of the terms and conditions set forth herein (collectively the "Terms of Use"). For a disclosure regarding information collected and shared by DigiKey from your access and use of the Site, visit DigiKey’s <a href='https://www.digikey.in/en/help/privacy?_gl=1*185m5gi*_up*MQ..&gclid=CjwKCAjwl6-3BhBWEiwApN6_krniM_pjYmmfsh2ZUIl9lgG-6W87lYYO--OL8yeL6-DL-0b7_Du4axoCFtkQAvD_BwE'>Privacy Notice</a>. By ordering Products through the Site or by mail, e-mail, phone, fax, or any other method, you agree on your behalf personally and on behalf of any entity for which you are an agent or you appear to represent to the Terms of Use and the Conditions of Order (as defined below).</b></p>
      <h4>I. Website Terms of Use</h4>
      <p><b>1. Access to the Site.</b> Registration is not required to place an order or to use the Site. Select portions of the Site offer expanded Services via the Web through a name/password protected system, including without limitation, the Web Services Applications.</p>
      <p>
        Your username and password are referred to as your "Identification." Your Identification must be accurate, current, and complete, and you may not provide false information to DigiKey or impersonate another individual or entity. You are solely responsible for keeping your Identification confidential. You agree that you and your authorized representatives will be the only users of your Identification, and that you will be solely responsible for all activities on the Site using your Identification. We strongly recommend that you log out of the Site and close your browser window when your session is completed to help prevent unauthorized persons from accessing your Identification. DigiKey will be entitled to monitor your Identification and, at its discretion, require you to change it. Please contact DigiKey immediately at <b><a href='mailto:internet.registration@digikey.com'>mailto:internet.registration@digikey.com</a></b> if you believe that your Identification has been lost or stolen, or that someone may attempt to use your Identification without your consent. Please keep in mind that no Internet site is 100% secure. Thus, while DigiKey strives to protect the personal information and privacy of its users, your use of the Site to transmit or store personally identifiable information is at your own risk.</p>
        <p><b>2. Intellectual Property.</b> The Services, the Site, and all information, Web Services Applications, Software, data, the DigiKey product database, printed and electronic documentation, content that you see, hear or otherwise experience on the Site, and all compilations thereof (the "<b>Content</b>") are protected by U.S. and international copyright, trademark and other laws, and belong to DigiKey or its partners, affiliates, licensors, suppliers, contributors, or third parties.</p>
        <p>Subject to these Terms of Use, and with the exception of Software and Web Services Applications, DigiKey grants you a personal, revocable, non-exclusive, non-transferable license to use the Site, the Services and the Content and to download, print and store portions of the Content. No right, title or interest in any accessed or downloaded Content or materials is transferred to you as a result of this license. DigiKey reserves all of its intellectual property rights in any Content you access or download from the Site, subject to this limited license as set forth herein.</p>
        
        <p>No other rights or licenses whether express or implied, including, without limitation, any implied patent licenses, are granted by DigiKey. Any unauthorized reproduction or redistribution of the Software is expressly prohibited by law, and may result in severe civil and criminal penalties. Violators may be prosecuted to the maximum extent permitted by law. All licenses granted herein are subject to the following restrictions: (1) you may only use these copies of the Content for your own internal business purposes or your personal, non-commercial use; (2) you may not copy or post the Content on any network computer or transmit, distribute, publish, display, or broadcast the Content in any media; and (3) you may not modify, translate, decompile, disassemble, reverse engineer, or alter the Site or the Content in any way, or delete or change any copyright, trademark, or other proprietary notice. WITHOUT LIMITING THE FOREGOING, COPYING OR REPRODUCTION OF THE SOFTWARE OR WEB SERVICES APPLICATIONS TO ANY OTHER SERVER OR LOCATION FOR FURTHER REPRODUCTION OR REDISTRIBUTION IS EXPRESSLY PROHIBITED. You acknowledge that the Software, Web Services Applications and any accompanying documentation and/or technical information, is subject to applicable export control laws and regulations of the United States of America. You agree not to export or re-export the Software, directly or indirectly, to any countries that are subject to USA export restrictions.</p>
        <p>You may not use any of the marks or logos appearing throughout the Site without express written consent from the trademark owner, except as permitted by applicable law.</p>
        <p>DigiKey may prohibit or limit your use of the Site including without limitation the Services, at any time in its sole discretion.</p>
        <p>You may not use any robot, scraper, spider, or other automated means to access or gather the Content from the Site, or mirror, co-brand, or frame the home page or any other pages of the Site on any other website or web page. For purposes of these Terms of Use, "co-branding" means to display a name, logo, trademark, or other means of attribution or identification of any party in such a manner as is reasonably likely to give a user the impression that such other party has the right to display, publish, or distribute the Site or its Content. Competitors and third party aggregators may not connect "deep links" to the Site, i.e., create links to this site that bypass the home page or other parts of the Site without the written permission of DigiKey. This prohibition is not intended to restrict the non-commercial activities of individuals.</p>
        <p><b>3. Disclaimer of Warranties.</b> DIGIKEY AND ITS RESPECTIVE SUPPLIERS MAKE NO EXPRESS OR IMPLIED WARRANTIES OR REPRESENTATIONS WITH RESPECT TO THE SITE, THE SERVICES OR THE CONTENT, AND DIGIKEY AND ITS SUPPLIERS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT WITH REGARD TO THE SITE, THE SERVICES, AND THE CONTENT. THE SOFTWARE AND WEB SERVICES APPLICATIONS ARE WARRANTED, IF AT ALL, ONLY ACCORDING TO THE TERMS OF THEIR RESPECTIVE LICENSE AGREEMENTS, IF ANY, AND ARE OTHERWISE SUBJECT TO THESE TERMS OF USE WARRANTY DISCLAIMER. DIGIKEY AND ITS SUPPLIERS DO NOT WARRANT THAT THE FUNCTIONS PERFORMED BY THE SITE OR THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, OR THAT DEFECTS IN THE SITE OR THE SERVICES WILL BE CORRECTED. DIGIKEY AND ITS SUPPLIERS DO NOT WARRANT THE ACCURACY OR COMPLETENESS OF THE CONTENT, OR THAT ANY ERRORS IN THE CONTENT WILL BE CORRECTED. THE SITE, THE SERVICES AND THE CONTENT ARE PROVIDED "AS-IS" AND ON AN "AS-AVAILABLE" BASIS. DIGIKEY AND ITS SUPPLIERS ARE NOT RESPONSIBLE FOR UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, ANY MATERIAL OR DATA SENT OR RECEIVED OR NOT SENT OR RECEIVED, OR ANY TRANSACTIONS ENTERED INTO THROUGH THE SITE. DIGIKEY AND ITS SUPPLIERS ARE NOT RESPONSIBLE FOR ANY CONTENT SENT USING AND/OR INCLUDED IN THE SITE BY ANY THIRD PARTY. ADVICE RECEIVED VIA THE SITE SHOULD NOT BE RELIED UPON FOR PERSONAL, MEDICAL, LEGAL OR FINANCIAL DECISIONS AND YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE TAILORED TO YOUR SITUATION. SOME JURISDICTIONS MAY NOT ALLOW THE EXLUSION OF CERTAIN TYPES OF WARRANTIES INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES. AS A RESULT, THE ABOVE LIMITATION OR EXLUSION MAY NOT APPLY TO YOU.</p>
        <p>See the Conditions of Order for all other Warranty information related to Products including Chip Outpost Products.</p>
        <p><b>4. Additional Disclaimers.</b> Without limiting the disclaimers set forth in Section 3 above:</p>
        <p><b>a. Applications Engineering.</b> DigiKey offers its applications engineering solely as a convenience to DigiKey customers. DigiKey applications engineering personnel strive to provide useful information regarding the Products. DigiKey does not guarantee that any information or recommendation provided is accurate, complete, or correct, and DigiKey shall have no responsibility or liability whatsoever in connection with any information or recommendation provided, or your reliance on such information or recommendation. You are solely responsible for analyzing and determining the appropriateness of any information or recommendation provided by DigiKey applications engineering personnel, or any other DigiKey personnel, and any reliance on such information or recommendation is at your sole risk and discretion. You acknowledge and agree that DigiKey may discuss the same or similar topics discussed with you with other DigiKey customers and provide the same or similar information or recommendations to other DigiKey customers. Without limiting the generality of the foregoing, any recommended substitutes or cross-references with respect to parts are simply recommendations, and DigiKey does not guarantee that such information or recommendations are accurate, complete or correct.</p>
        <p><b>b. Correction of Errors and Inaccuracies.</b> The Content may contain typographical errors or other errors or inaccuracies and may not be complete or current. DigiKey therefore reserves the right to correct any errors, inaccuracies or omissions and to change or update the Content at any time without prior notice. DigiKey does not, however, guarantee that any errors, inaccuracies or omissions will be corrected and is not obligated to make such corrections.</p>
        <p><b>c. Third Party Links and Promotions.</b> Hypertext links to third party websites or information do not constitute or imply an endorsement, sponsorship, or recommendation by DigiKey of the third party, the third-party website, or the information contained therein, unless expressly stated on the Site. You acknowledge and agree that DigiKey is not responsible for the availability of any such websites and that DigiKey does not endorse or warrant, and is not responsible or liable for, any such website or the content thereon. You are solely responsible for making your own decisions regarding your interactions or communications with any other website.</p>
        <p>Any dealings with third parties (including advertisers) included within or available via a link from the Site or participation in promotions, including the delivery of and the payment for goods and services, and any other terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and the advertiser or other third party. DigiKey is not responsible or liable for any part of any such dealings or promotions.</p>
        <p><b>d. Geographic Limitations on Use.</b> Like most Internet websites, this Site is accessible worldwide. However, not all Products or Services offered by DigiKey are available to all persons or in all geographic locations. DigiKey reserves the right to limit the provision of its Products and Services to any person, geographic area, or jurisdiction and to limit the quantities of any Products or Services that it provides. You agree to comply with all applicable laws and local rules regarding the transmission of technical data, acceptable content, and online conduct.</p>
        <p><b>e. Color Display.</b> DigiKey attempts to display as accurately as possible the colors of the Products shown on the Site. However, because the colors you see will depend on many factors, including your monitor or printer, DigiKey cannot guarantee that the color you see matches the Product color.</p>
        <p><b>5. Limitation of Liability.</b> IN NO EVENT SHALL DIGIKEY OR ITS SUPPLIERS BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS, LOST SAVINGS, OR LOSS OF BUSINESS OPPORTUNITY) ARISING OUT OF OR RELATING TO: (a) THE SITE, THE SERVICES, OR THE CONTENT, OR YOUR USE OF OR INABILITY TO USE THE SITE, THE SERVICES, OR THE CONTENT, (b) ANY TRANSACTION OR COMMUNICATIONS CONDUCTED THROUGH OR FACILITATED BY THE SITE; (c) ANY CLAIM ATTRIBUTABLE TO ERRORS, OMISSIONS, OR OTHER INACCURACIES IN THE SITE, THE SERVICES OR THE CONTENT, (d) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, (e) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SITE OR THE SERVICES, OR (f) ANY OTHER MATTER RELATING TO THE SITE, THE SERVICES, OR THE CONTENT; EVEN IF DIGIKEY OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SUBJECT TO THE FOREGOING, IN NO EVENT SHALL THE LIABILITY OF DIGIKEY AND ITS SUPPLIERS RELATING IN ANY WAY TO THE SITE, THE SERVICES, OR THE CONTENT EXCEED $100 OR THE MINIMUM AMOUNT ALLOWABLE UNDER APPLICABLE LAW, WHICHEVER IS GREATER, REGARDLESS OF THE LEGAL THEORY ASSERTED FOR SUCH LIABILITY, WHETHER IN CONTRACT, TORT, WARRANTY OR OTHERWISE.</p>
        <p>IF YOU ARE DISSATISFIED WITH THE SITE, THE SERVICES, THE CONTENT, OR WITH THE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE, THE SERVICES, AND/OR THE CONTENT.</p>
        <p>Any cause of action against DigiKey or its suppliers with respect to the Site, the Services, or the Content must be instituted within one (1) year from the date on which the claim arose.</p>
        <p>Some States, including New Jersey (as to consumers), may not allow the exclusion or limitation of certain types of damages such as incidental or consequential damages, so the above limitation or exclusion may not apply to you, but in any event shall apply to the maximum extent allowed by law.</p>
        <p>See the Conditions of Order for all other Limitations of Liability information related to Products including Chip Outpost Products.</p>
        <p><b>6. Indemnification.</b> You understand and agree that you are personally responsible for your reliance upon any information or recommendation provided on this Site, the Content, by DigiKey applications engineering personnel, your behavior on the Site, and your Submissions. You agree to indemnify, defend and hold harmless DigiKey and DigiKey's joint venturers, business partners, suppliers, licensors, licensees, affiliates, employees, agents, officers, directors, owners, representatives and any third-party information, Software, Content, and Web Services Application providers to the Site and Services from and against all claims, losses, expenses, damages and costs (including, but not limited to, direct, incidental, special, consequential, punitive, exemplary and indirect damages), and reasonable attorneys' fees, resulting from or arising out of your use, misuse, or inability to use the Site, the Services (including, without limitation, the Communication Services), or the Content, your reliance upon any information or recommendation provided by DigiKey applications engineering personnel, your submissions (as defined in Section 9 below), or any violation by you of these Terms of Use.</p>
        <p><b>7. Additional Prohibited User Conduct.</b> You are prohibited from compromising the security or tampering with system resources and accounts related to the Site. The use or distribution of tools designed for compromising security (e.g., password guessing manually or through programs, cracking tools, or network probing tools) is strictly prohibited. DigiKey may monitor your use of the Site including, without limitation, the Services, to ensure your compliance with these Terms of Use. If you become involved, or are suspected to have become involved, in any violation of these Terms of Use, DigiKey reserves the right to investigate your activities for its own purposes and release the details of your violations to others in DigiKey’s sole discretion, including, without limitation, to governmental authorities, private investigators, and other users of the Site to assist them in resolving security incidents.</p>
        <p>You agree not to use the Site in any manner that violates any laws or infringes the intellectual property of, or interferes with the rights of, third parties. You may not take any action that imposes, or may impose in DigiKey's sole discretion, an unreasonable or disproportionately large load on the Site's infrastructure or interfere or attempt to interfere with the proper working of the Site or any activities conducted on the Site, or bypass any robot exclusion headers or other measures DigiKey may use to prevent or restrict access to the Site.</p>
        <p>DigiKey reserves the right to fully cooperate with any law enforcement authorities or court order requesting or directing DigiKey to disclose the identity of anyone violating the security of the Site or these Terms of Use.</p>
        <p><b>8. Use of Communication and Project Management Services.</b> The Site may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, a project management platform, builder and configuration tools, calendars and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, "Communication Services"). You agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service. By way of example, and not as a limitation, you agree that when using a Communication Service, you will not:</p>
        <ul>
          <li><p id='two'>Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others including without limitation engaging in activity that incites discrimination, hate or violence towards one person or a group because of their belonging to a race, ethnicity, gender, sexual orientation, physical ability, age, religion or nationality or that insults the victims of crimes against humanity by contesting the existence of those crimes.</p></li>
          <li><p id='two'>Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, obscene, indecent or unlawful topic, material, or information.</p></li>
          <li><p id='two'>Upload, display, or otherwise make available files that contain images, photos, software, object code, source code, markup language, libraries, schematics, specifications, designs, PCB design files, PCB fabrication files, Gerber files, or other material that infringes any copyright, trademark, patent, trade secret, privacy right, publicity right, confidentiality obligation or other proprietary or intellectual property right of any party.</p></li>
          <li><p id='two'>Upload files that contain viruses, malware, ransomware, corrupted files, or any other similar software or programs that may damage or interrupt the operation of another's computer or the Site.</p></li>
          <li><p id='two'>Use or upload any material or information, including images, software, object codes, source code, markup language, libraries, schematics, specifications, designs, PCB design files, PCB fabrication files, Gerber files, or photographs, which is made available through the Site in any manner that infringes any copyright, trademark, patent, trade secret, privacy right, publicity right, confidentiality obligation or other proprietary or intellectual property right of any party.</p></li>
          <li><p id='two'>Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages.</p></li>
          <li><p id='two'>Conduct or forward surveys, contests, pyramid schemes or chain letters.</p></li>
          <li><p id='two'>Download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner</p></li>
          <li><p id='two'>Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</p></li>
          <li><p id='two'>Restrict or inhibit any other user from using and enjoying the Communication Services.</p></li>
          <li><p id='two'>Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service.</p></li>
          <li><p id='two'>Harvest or otherwise collect information about others, including e-mail addresses, without their consent.</p></li>
          <li><p id='two'>Violate any applicable laws or regulations.</p></li>
          <li><p id='two'>Create a false identity for the purpose of misleading others.</p></li>
        </ul>
        <p>DigiKey has no obligation to monitor the Communication Services. However, DigiKey reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. DigiKey reserves the right to terminate your access to the Site, Services, Content, and any or all of the Communication Services at any time without notice for any reason whatsoever. DigiKey reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in DigiKey's sole discretion. Always use caution when giving out any personally identifying information about yourself in any Communication Service. DigiKey does not control or endorse the content, messages or information found in any Communication Service and DigiKey specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination, and you are responsible for adhering to such limitations if you download the materials.</p>
        <p><b>9. User Supplied Information.</b> DigiKey does not claim ownership of the materials, including without limitation, text, images, photos, software, object code, source code, markup language, libraries, schematics, specifications, designs, PCB design files, PCB fabrication files, Gerber files, or other material you or other users of Communication Services provide to DigiKey (including feedback and suggestions) or post, upload, input, or submit to the Site or its associated services (collectively "Submissions"). However, by posting, uploading, inputting, providing or submitting your Submission you are granting DigiKey, its affiliated companies and licensees (including without limitation any supplier of and service provider used in connection with the DigiKey, Tech-Xchange, Project Sites, or eewiki.net websites) a royalty-free, irrevocable, perpetual, worldwide license to your Submission including, without limitation, the rights to use, copy, distribute, transmit, publicize, publicly perform, reproduce, translate, reformat or otherwise edit or modify, display and create derivative works from this material, in any and all media whether known now or later developed, in any manner, in whole or in part, without any restriction or responsibilities to you, and to publish your name, likeness, pseudonym, or other identifier in connection with your Submission. Notwithstanding the foregoing, DigiKey will not use your projects submitted to Project Sites website to commercialize a product without your permission.</p>
       
        <p>By posting, uploading, inputting, providing or submitting your Submission you represent and warrant that your Submission, and use thereof in accordance with these Terms of Use, complies with all applicable laws and that you own or otherwise control all of the rights in and to your Submission including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions and grant the license you provide in these Terms of Use, and that the Submission, and the use thereof in accordance with these Terms of Use, does not and will not infringe, misappropriate or violate any right of any person or entity, including without limitation, any copyright, trademark, patent, trade secret, design right, right of privacy, right of publicity, or any intellectual property rights.</p>
        <p>You further represent, warrant and agree that:</p>
        <ul>
          <li><p id='two'>Any Submission does not constitute a "defense article" or "defense service" as such terms are defined in the International Traffic in Arms Regulations (the "ITAR"), 22 CFR Parts 120-130, administered by the Directorate of Defense Trade Controls, U.S. Department of State ("DDTC"), and is not otherwise (i) subject to the ITAR, (ii) an item on the U.S. Munitions List (as such term is defined in the ITAR), or (iii) under the jurisdiction of DDTC;</p></li>
          <li><p id='two'>If applicable, you have provided DigiKey with the correct and accurate Export Control Classification Number ("ECCN") as such term is defined in the Export Administration Regulations, 15 CFR Parts 730-774; and</p></li>
          <li><p v>All Submissions are correct and accurate.</p></li>
        </ul>
        <p><b>10. Notices and Procedure for Making Claims of Copyright Infringement.</b> Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement should be sent to the Service Provider's Designated Agent. ALL INQUIRIES NOT RELEVANT TO THE FOLLOWING PROCEDURE WILL RECEIVE NO RESPONSE.</p>
        <p>NOTE: THE FOLLOWING INFORMATION IS PROVIDED EXCLUSIVELY FOR NOTIFYING THE SERVICE PROVIDERS REFERENCED BELOW THAT YOUR COPYRIGHTED MATERIAL MAY HAVE BEEN INFRINGED. ALL OTHER INQUIRIES, SUCH AS REQUESTS FOR ENGINEERING ASSISTANCE, REPORTS OF EMAIL ABUSE, AND PIRACY REPORTS, WILL NOT RECEIVE A RESPONSE THROUGH THIS PROCESS.</p>
        <p>Written notification must be submitted to the following Designated Agent:</p>
        <p><b>Service Provider(s):</b> Digi-Key Corporation</p>
        <p><b>Name of Agent Designated to Receive Notification of Claimed Infringement:</b> Ross West</p>
        <p><b>Full Address of Designated Agent to Which Notification Should be Sent: </b>701 Brooks Avenue South, Thief River Falls, MN 56701 USA</p>
        <p><b>Telephone Number of Designated Agent: </b>1-800-344-4539 or 218-681-6674</p>
        <p><b>Facsimile Number of Designated Agent: </b>218-681-3380</p>
        <p><b>Email Address of Designated Agent:</b> <a href='mailto:copyrightclaims@digikey.com'>copyrightclaims@digikey.com</a></p>
        <p>To be effective, the Notification must include the following:</p>
        <ol>
          <li><p id='two'>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed ("<b>Complaining Party</b>");</p></li>
          <li><p id='two'>Identification of the copyrighted work claimed to have been infringed, or if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p></li>
          <li><p id='two'>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material;</p></li>
          <li><p id='two'>Information reasonably sufficient to permit the service provider to contact the Complaining Party, such as an address, telephone number, and if available, an electronic mail address at which the complaining party may be contacted;</p></li>
          <li><p id='two'>A statement that the Complaining Party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p></li>
          <li><p id='two'>A statement that the information in the notification is accurate, and under penalty of perjury, that the Complaining Party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p></li>
        </ol>
          <p>Upon receipt of the written Notification containing the information as outlined in 1 through 6 above:</p>
          <ol>
            <li><p id='two'>Service Provider shall remove or disable access to the material that is alleged to be infringing;</p></li>
            <li><p id='two'>Service Provider shall forward the written notification to such alleged infringer ("<b>Subscriber</b>");</p></li>
            <li><p id='two'>Service Provider shall take reasonable steps to promptly notify the Subscriber that it has removed or disabled access to the material.</p></li>
          </ol>
          <p><b>11. Confidentiality.</b> You shall not disclose DigiKey Confidential Information for so long as the information retains its confidential nature. As used in these Terms of Use, "DigKey Confidential Information" means all nonpublic information disclosed by DigiKey through the Web Services Applications, the Site, or Software that is designated as confidential or that, given the nature of the information or circumstances surrounding its disclosure, reasonably should be understood to be confidential. You shall not use, or allow the use of, DigiKey Confidential Information except as expressly permitted hereunder. DigiKey Confidential Information includes, without limitation, nonpublic information relating to DigiKey or DigiKey's business partners' sales, margin percentage, margin numbers, technology, customers, business plans, promotional and marketing activities, finances and other business affairs (including, but not limited to, any information about or involving one of DigiKey's so-called beta tests or a beta test product that you obtain as a result of your participation in such beta test) and third-party information that DigiKey is obligated to keep confidential. Notwithstanding any other provision in this Section, you shall not have any confidentiality obligation to DigiKey under this Section above with respect to any information that is or becomes publicly available without breach of these Terms of Use, can be shown by documentation to have been lawfully known by you at the time of its receipt from DigiKey, is received from a third party who did not acquire or disclose the same by a wrongful or tortious act, or can be shown by documentation to have been independently developed by you without the use or reliance on DigiKey Confidential Information in any way whatsoever.</p>

          
          
          <p><em>Governing Version</em></p>
          <p><em>he English version of these Conditions of Order shall prevail wherever there is a discrepancy between the English version and any other language version.</em></p>
          <p><em>© 2024, Digi-Key Corporation. All rights reserved.</em></p>
          <p><b>QUESTIONS OR ADDITIONAL INFORMATION.</b> If you have questions regarding Conditions of Order or wish to obtain additional information, please send an e-mail to <a href='mailto:international.customer.service@digikey.com'>international.customer.service@digikey.com.</a></p>
          <p><strong>DATE OF LAST MODIFICATION</strong></p>
          <p><b>2024-03-26</b></p>
          {/* Add checkboxes */}
          <div className="checkbox-section">
            <label className="checkbox-label">
              <input
              type="checkbox"
              checked={checkedTerms}
              onChange={handleTermsChange}
              />
              I agree to the Terms and Conditions
            </label>
            <label className="checkbox-label">
              <input
              type="checkbox"
              checked={checkedPrivacy}
              onChange={handlePrivacyChange}
              />
              I agree to the Privacy Policy
              </label>
          </div>
          <footer>
            <h5>Follow us on</h5>
            <a className='sm' href='www.instagram.com'>instagram</a>
            <a className='sm' href='www.twitter.com'>twitter</a>
            <a className='sm' href='www.facebook.com'>facebook</a>
            </footer>
        </div>
        </>
  );
};


export default TermsAndConditions;
